# Generated by Django 5.0.3 on 2024-09-10 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agendamento', '0002_medico_agendamento_observacoes_agendamento_medico'),
    ]

    operations = [
    ]
