# Generated by Django 5.0.3 on 2024-09-09 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Agendamento',
        ),
    ]
